# Generated by Django 4.2.6 on 2023-12-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(max_length=7)),
                ('voltage', models.FloatField(max_length=7)),
                ('current', models.FloatField(max_length=7)),
                ('electricity', models.FloatField(max_length=7)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
