# Generated by Django 4.2.6 on 2023-12-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_consumption_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='current',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='electricity',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='power',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.CharField(max_length=7),
        ),
    ]
